name: zola-deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build:
    name: build-site
    runs-on: ubuntu-latest
    steps:
      - name: checkout-main
        uses: actions/checkout@v4
      - name: build-and-deploy
        uses: shalzz/zola-deploy-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
